name: Pull Request
on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '16'
          - '14'
        node-red:
          - '^3'
          - '^2'
          - '~2.1'
          - '~2.0'
    name: Tests (Node ${{ matrix.node }} - node-red ${{ matrix.node-red }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Install exact version of node-red
        run: npm install --save-dev node-red@${{ matrix.node-red }}
      - name: Run tests
        run: npm run ci:test
